### ISSUE TITLE
Set up background graphics

### ISSUE THREAD

**Issue by mtwete** [mtwete/MNMS-ArtilleryGame#3]
As a player I want to have background graphics for the different screens in the game so it is clear when you have left the main menu and I can see the environment of the level I am playing on. The backgrounds should be static and fit properly on the screen. The background for the main menu should be different than the background seen during gameplay. The background should not cover up the players tank, the targets, or the bullets/shells.

**Comment by queoui** [comment]
Size S: 0-2days
